server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: loan-microservice
          uri: lb://LOAN-MICROSERVICE
          predicates:
            - Path=/loan/**
        - id: document-microservice
          uri: lb://DOCUMENT-MICROSERVICE
          predicates:
            - Path=/document/**
        - id: client-microservice
          uri: lb://CLIENT-MICROSERVICE
          predicates:
            - Path=/client/**